- name: api changes
  color: '5663e9'
- name: api support
  color: '5663e9'
- name: guide
  color: fbca04
- name: backlog
  color: 7ef7ef
- name: backport
  color: 88aabb
- name: blocked
  color: fc1423
- name: bug
  color: d73a4a
- name: chore
  color: ffffff
- name: ci
  color: 0075ca
- name: dependencies
  color: 276bd1
- name: discussion
  color: b6b1f9
- name: documentation
  color: 0075ca
- name: duplicate
  color: cfd3d7
- name: error handling
  color: 80c042
- name: feature request
  color: fcf95a
- name: good first issue
  color: 7057ff
- name: has PR
  color: 4b1f8e
- name: help wanted
  color: 008672
- name: in progress
  color: ffccd7
- name: in review
  color: aed5fc
- name: invalid
  color: e4e669
- name: 'need more info'
  color: '80c042'
- name: performance
  color: 80c042
- name: permissions
  color: 80c042
- name: priority:high
  color: fc1423
- name: question (please use Community Server instead)
  color: d876e3
- name: ratelimits
  color: 80c042
- name: refactor
  color: 1d637f
- name: semver:major
  color: c10f47
- name: semver:minor
  color: e4f486
- name: semver:patch
  color: e8be8b
- name: tests
  color: f06dff
- name: typings
  color: 80c042
- name: utility
  color: 80c042
- name: wontfix
  color: ffffff